# pyright: reportMissingTypeArgument=false
# pyright: reportPrivateUsage=false, reportAttributeAccessIssue=false, reportUnknownMemberType=false
"""Tests for view_model - auto-generated from Variable fields."""

import pytest
from assertpy import assert_that
from PySide6.QtWidgets import QLabel

from qtpie import Variable, Widget, new, widget
from qtpie.testing import QtDriver


class TestViewModelAutoGenerated:
    """Test view_model auto-generation from Variable fields."""

    def test_view_model_exists(self, qt: QtDriver) -> None:
        """Widget has a view_model property."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("")

        w = qt.track(MyWidget())
        assert_that(w.view_model).is_not_none()

    def test_view_model_contains_variables(self, qt: QtDriver) -> None:
        """view_model contains all Variable fields."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("hello")
            _count: Variable[int] = new(42)

        w = qt.track(MyWidget())

        # Access Variables through view_model
        assert_that(w.view_model._name.value).is_equal_to("hello")
        assert_that(w.view_model._count.value).is_equal_to(42)

    def test_view_model_excludes_non_variables(self, qt: QtDriver) -> None:
        """view_model does not contain non-Variable fields."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("")
            _label: QLabel = new("Hello")

        w = qt.track(MyWidget())

        # Variable is accessible
        assert_that(w.view_model._name).is_not_none()

        # QLabel is not accessible through view_model
        with pytest.raises(AttributeError):
            _ = w.view_model._label

    def test_view_model_is_same_instance(self, qt: QtDriver) -> None:
        """view_model returns the same instance on repeated access."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("")

        w = qt.track(MyWidget())

        vm1 = w.view_model
        vm2 = w.view_model
        assert_that(vm1).is_same_as(vm2)

    def test_view_model_variables_are_same_as_widget(self, qt: QtDriver) -> None:
        """view_model Variables are the same as widget Variables."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("")

        w = qt.track(MyWidget())

        # They should be the exact same Variable instance
        assert_that(w.view_model._name).is_same_as(w._name)

    def test_view_model_changes_reflect_on_widget(self, qt: QtDriver) -> None:
        """Changes via view_model are visible on widget."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("")

        w = qt.track(MyWidget())

        w.view_model._name.value = "changed"
        assert_that(w._name.value).is_equal_to("changed")

    def test_widget_changes_reflect_on_view_model(self, qt: QtDriver) -> None:
        """Changes via widget are visible on view_model."""

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("")

        w = qt.track(MyWidget())

        w._name.value = "changed"
        assert_that(w.view_model._name.value).is_equal_to("changed")


class TestViewModelWithBindings:
    """Test view_model with bind()."""

    def test_bind_via_view_model(self, qt: QtDriver) -> None:
        """Can bind using view_model Variables."""
        from qtpie import bind

        @widget
        class MyWidget(Widget):
            _name: Variable[str] = new("Hello")
            _label: QLabel = new("")

            def __setup__(self) -> None:
                bind(self.view_model._name).to(self._label)

        w = qt.track(MyWidget())
        assert_that(w._label.text()).is_equal_to("Hello")

        # Update via view_model
        w.view_model._name.value = "World"
        assert_that(w._label.text()).is_equal_to("World")
