[project]
dependencies = [
  "poethepoet>=0.40.0",
  "pytest-asyncio>=1.3.0",
]
description = "Add your description here"
name = "v2-prototyping"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[tool.poe.tasks]
forc1 = {cmd = "uv run src/forc/app/__main__.py", cwd = "examples/forc"}
forc2 = {cmd = "uv run src/forc2/app/__main__.py", cwd = "examples/forc2"}
qrc1 = {cmd = "pyside6-rcc -o src/forc/app/qrc_resources.py resources/resources.qrc", cwd = "examples/forc"}
qrc2 = {cmd = "pyside6-rcc -o src/forc2/app/qrc_resources.py resources/resources.qrc", cwd = "examples/forc2"}
test-apis = "uvicorn main:app --app-dir examples/test-apis"

[tool.uv.workspace]
members = [
  "lib",
  "tests",
  "examples/forc",
  "examples/forc/src",
  "examples/forc/tests",
  "examples/forc/test-apis",
  "examples/forc2",
  "examples/forc2/src",
  "examples/forc2/tests",
  "examples/test-apis",
]

[tool.uv.sources]
forc = {workspace = true}
forc2 = {workspace = true}
qtpie = {workspace = true}

[dependency-groups]
dev = [
  "assertpy>=1.1",
  "fastapi>=0.128.0",
  "mkdocs-material>=9.7.1",
  "mypy>=1.19.1",
  "pydantic>=2.12.5",
  "pyright>=1.1.407",
  "pyside6>=6.10.1",
  "pytest>=9.0.2",
  "pytest-cov>=7.0.0",
  "pytest-qt>=4.5.0",
  "pytest-sugar>=1.1.1",
  "python-multipart>=0.0.21",
  "qtpie[test]",
  "ruff>=0.14.10",
  "uvicorn>=0.40.0",
]

[tool.pyright]
exclude = ["v1/", "**/.venv/", "examples/test-apis/", "**/qrc_resources.py"]
extraPaths = ["examples/forc/test-apis"]
pythonPlatform = "All"
pythonVersion = "3.13"
reportPrivateImportUsage = false
typeCheckingMode = "strict"
venv = ".venv"
venvPath = "."

# Analyze unannotated functions (so you still get checking),
# but DO NOT require explicit return annotations.
analyzeUnannotatedFunctions = true

# Ban unknown / untyped stuff everywhere
reportMissingParameterType = "error"
reportMissingTypeArgument = "error"
reportUnknownArgumentType = "error"
reportUnknownLambdaType = false
reportUnknownMemberType = "error"
reportUnknownParameterType = "error"
reportUnknownVariableType = "error"

# Catch assignment to undeclared attributes
reportAttributeAccessIssue = "error"

# Extra pedantic goodness
reportImplicitOverride = "error"
strictDictionaryInference = true
strictListInference = true
strictParameterNoneValue = true
strictSetInference = true

[tool.ruff]
exclude = ["**/qrc_resources.py"]
line-length = 200
target-version = "py314"

[tool.ruff.lint]
ignore = []
select = [
  "E", # pycodestyle errors
  "F", # pyflakes
  "I", # isort-style import rules
  "B", # flake8-bugbear: common bugs & gotchas
  "UP", # pyupgrade: use modern Python features
]

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"

[tool.ruff.lint.isort]
known-first-party = ["qtpie"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["*/tests/*", "*/__init__.py"]
source = ["lib/qtpie"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError",
  "@overload",
]
