"""QtPie utility modules for shared functionality."""

from qtpie.utils.common import (
    HANDLER_SPEC_RE,
    PLACEHOLDER_RE,
    detect_required_bindings,
    is_primitive_type,
    is_signal,
    is_signal_on_type,
)
from qtpie.utils.layouts import (
    IconType,
    add_to_layout,
    apply_layout_margins,
    apply_object_name_and_classes,
    apply_widget_props,
    create_layout,
    resolve_icon,
    resolve_margins,
)
from qtpie.utils.properties import resolve_nested_property
from qtpie.utils.type_checks import (
    is_dock_generic,
    is_model_widget,
    is_qaction,
    is_qcombobox,
    is_qgroupbox,
    is_qlayout,
    is_qlistview,
    is_qobject,
    is_qspaceritem,
    is_qsplitter,
    is_qtableview,
    is_qtabwidget,
    is_qtreeview,
    is_qwidget,
)

__all__ = [
    "HANDLER_SPEC_RE",
    "PLACEHOLDER_RE",
    "IconType",
    "add_to_layout",
    "apply_layout_margins",
    "apply_object_name_and_classes",
    "apply_widget_props",
    "create_layout",
    "detect_required_bindings",
    "is_dock_generic",
    "is_model_widget",
    "is_primitive_type",
    "is_qaction",
    "is_qcombobox",
    "is_qgroupbox",
    "is_qlayout",
    "is_qlistview",
    "is_qobject",
    "is_qspaceritem",
    "is_qsplitter",
    "is_qtabwidget",
    "is_qtableview",
    "is_qtreeview",
    "is_qwidget",
    "is_signal",
    "is_signal_on_type",
    "resolve_icon",
    "resolve_margins",
    "resolve_nested_property",
]
